import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
   return (
      <div>
         <Head>
            <title>Akame</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
         </Head>
         <div><a href="#">Home Page || Akame AniApi!!</a></div>
      </div>
   )
}

export default Home
