import React, { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import HomeBanner from '@/components/shared/HomeBanner'
import { Anime } from '@/types'
import AnimeApi from '@/api/getAnime'
import Loading from '@/components/shared/Loading'

const Home: NextPage = () => {
   const [ trendingAnime, setTrendingAnime ] = useState<Anime[]>([]);
   const [ loading, setLoading ] = useState<boolean>(true)
   useEffect(() => {
      const fetchAnimeTrending = async () => {
         try {
            const variables = {
               type: 'ANIME',
               perPage: 15,
               sort: 'TRENDING_DESC'
            }
            const response: any = await AnimeApi.getAnime(variables)
            console.log('Fetch Anime successfully');
            setTrendingAnime(response.data.Page.media);
            setLoading(false)
         } catch(err) {
            console.log('Failed to Anime product list: ', err);
         }
      }
      fetchAnimeTrending();
   }, [])
   return (
      <div>
         <Head>
            <title>Akame - Anime</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.jpeg" />
         </Head>
         {loading ? <Loading /> : <HomeBanner type='anime' data={trendingAnime} />}
      </div>
   )
}

export default Home;
