import React from 'react'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { ApolloClient, gql, InMemoryCache } from '@apollo/client'
import HomeBanner from '@/components/shared/HomeBanner'
import { Manga } from '@/types'


interface HomeProps {
  trendingManga: Manga[];
}
const Manga: NextPage<HomeProps> = ({
  trendingManga
}) => {
   return (
      <div>
         <Head>
            <title>Akame</title>
            <meta name="description" content="Generated by create next app" />
            {/* <link rel="icon" href="/favicon.ico" /> */}
         </Head>
         <HomeBanner type='manga' data={trendingManga} />
      </div>

   )
}
export const getStaticProps: GetStaticProps = async () => {
   const query = gql `
      query ($page: Int, $perPage: Int, $search: String, $type: MediaType) {
         Page(page: $page, perPage: $perPage) {
            pageInfo {
               total
               currentPage
               lastPage
               hasNextPage
               perPage
            }
            media(
               search: $search
               type: $type
               sort: POPULARITY_DESC
            ) {
               description
               trailer {
                  id
                  site
               }
               id
               idMal
               title {
                  romaji
                  english
                  native
                  userPreferred
               }
               coverImage {
                  extraLarge
                  large
                  medium
                  color
               }
               startDate {
                  year
                  month
                  day
               }
               trending
               popularity
               favourites
               bannerImage
               season
               seasonYear
               format
               status(version: 2)
               chapters
               episodes
               duration
               genres
               isAdult
               countryOfOrigin
               averageScore
               synonyms
               studios {
                  edges {
                  id
                  isMain
                  node {
                     id
                     name
                     isAnimationStudio
                     favourites
                  }
                  }
               }
               characters(sort: ROLE) {
                  edges {
                  id
                  name
                  role
                  voiceActors {
                     id
                     name {
                        first
                        middle
                        last
                        full
                        native
                        userPreferred
                     }
                     primaryOccupations
                     language: languageV2
                     image {
                        large
                        medium
                     }
                     gender
                     dateOfBirth {
                        year
                        month
                        day
                     }
                     dateOfDeath {
                        year
                        month
                        day
                     }
                     age
                     yearsActive
                     homeTown
                     bloodType
                     favourites
                  }
                  node {
                     id
                     name {
                        first
                        middle
                        last
                        full
                        native
                        userPreferred
                     }
                     image {
                        large
                        medium
                     }
                     gender
                     dateOfBirth {
                        year
                        month
                        day
                     }
                     age
                     favourites
                     bloodType
                  }
                  }
               }
               relations {
                  edges {
                  relationType(version: 2)
                  node {
                     id
                     type
                  }
                  }
               }
               recommendations(sort: RATING_DESC) {
                  nodes {
                  mediaRecommendation {
                     id
                     type
                  }
                  }
               }
               airingSchedule(notYetAired: true) {
                  nodes {
                  airingAt
                  episode
                  mediaId
                  id
                  }
               }
               tags {
                  name
               }
            }
         }
      }
   `;
   const client = new ApolloClient({
      uri: 'https://graphql.anilist.co',
      cache: new InMemoryCache(),
   });
   const { data: trendingManga } = await client.query({
      query: query,
      variables: {
         type: 'MANGA',
         perPage: 15
      }
   })
   return {
      props: {
         trendingManga: trendingManga.Page.media,
      }
   }
}

export default Manga
