import React, { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import HomeBanner from '@/components/shared/HomeBanner'
import { Manga } from '@/types'
import AnimeApi from '@/api/getAnime'
import Loading from '@/components/shared/Loading'

const Manga: NextPage = () => {
   const [ trendingManga, setTrendingManga ] = useState<Manga[]>([]);
   const [ loading, setLoading ] = useState<boolean>(true)
   useEffect(() => {
      const fetchAnimeTrending = async () => {
         try {
            const variables = {
               type: 'MANGA',
               perPage: 15,
               sort: 'TRENDING_DESC'
            }

            const response: any = await AnimeApi.getAnime(variables)
            console.log('Fetch Anime successfully');
            setTrendingManga(response.data.Page.media);
            setLoading(false)
         } catch(err) {
            console.log('Failed to Anime product list: ', err);
         }
      }
      fetchAnimeTrending();
   }, [])
   return (
      <div>
         <Head>
            <title>Akame - Manga</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.jpeg" />
         </Head>
         {loading ? <Loading /> : <HomeBanner type='manga' data={trendingManga} />}
      </div>
   )
}

export default Manga;
