import React from 'react'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import HomeBanner from '@/components/shared/HomeBanner'
import { Anime } from '@/types'
import AnimeApi from '@/api/AnilistApi'

interface HomaPage {
   trendingManga: Anime[];
}

const Manga: NextPage<HomaPage> = ({
   trendingManga
}) => {
   return (
      <div>
         <Head>
            <title>Akame - Manga</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.jpeg" />
         </Head>
         <HomeBanner type='manga' data={trendingManga} />
      </div>
   )
}

export const getServerSideProps: GetServerSideProps = async () => {
   const { data: trendingManga } = await AnimeApi.getAnime({
      type: 'MANGA',
      perPage: 15,
      sort: 'TRENDING_DESC'
   })
   return {
      props: {
         trendingManga: trendingManga.Page.media
      }
   }
}

export default Manga;
